version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: "${PROJECT_NAME}_wordpress"
    restart: always
    ports:
      - "9000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./../resources/wordpress:/var/www/html
      - ./wordpress/.htaccess:/var/www/html/.htaccess

  db:
    image: mysql:5.7
    container_name: "${PROJECT_NAME}_wordpress_db"
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - ./../resources/db:/var/lib/mysql
